json.name contact.name
json.middle_name contact.middle_name
json.street_address contact.street_address
json.city contact.city
json.state contact.state
json.zip contact.zip
json.email contact.email
json.phone contact.phone
json.create_time contact.friendly_updated_at
json.full_name contact.full_name